# Generated by Django 4.1.7 on 2023-03-10 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='event',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='participant',
        ),
        migrations.AddField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='certificator.event'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='participant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='certificator.participant'),
        ),
    ]
