# Generated by Django 4.1.7 on 2023-03-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificator', '0002_remove_certificate_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
