# Generated by Django 4.1.7 on 2023-03-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificator', '0005_alter_event_event_type_alter_eventtype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificator.eventtype'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
