# Generated by Django 4.1.7 on 2023-03-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificator', '0006_alter_event_event_type_alter_eventtype_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_participants',
            field=models.ManyToManyField(null=True, to='certificator.participant'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
