# Generated by Django 4.1.7 on 2023-03-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificator', '0010_certificate_remove_event_event_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='event',
        ),
        migrations.AddField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificator.event'),
        ),
    ]
