# Generated by Django 4.1.7 on 2023-03-24 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificator', '0011_remove_certificate_event_certificate_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificator.event'),
        ),
    ]
