# Generated by Django 4.1.7 on 2023-03-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificator', '0012_alter_certificate_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='certificate_number',
            new_name='id',
        ),
    ]
